### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by rthrash** [modxcms/a11y#11]
Need to determine overall navigation and keyboard shortcuts for the main workflow

- [ ] According to the ARIA Authoring Practices, Shift+F10 should pop open and focus the context menu within a web app.

**Comment by dubrod** [comment]
@TheBoxer can you put a list of the current manager keyboard shortcuts here so we can see what else is needed and have our associates test them?

**Comment by TheBoxer** [comment]
I know only about

* `cmd + s` - Save document
* `cmd + shit + u` - Clear cache

**Comment by dubrod** [comment]
ok so that leaves it wide open for discussion:

- delete document
- unpublish document
- hide from menus

seem like suitable time savers for non mouse users

**Comment by dubrod** [comment]
then we have the need for quick ui navigation:

- open search div
- focus on resource tree
- focus on element tree
- focus on file tree
- focus on top menu

all seem like suitable time savers as well

**Comment by paulbohman** [comment]
In terms of being able to focus on different sections of the document,
keyboard shortcuts could be useful, for sure. You should also map those
same sections to aria landmark roles and give them appropriate labels. Here
are some suggestions to consider:

role="search"
role="navigation" aria-label="top menu"
role="navigation" aria-label="resource tree"
role="navigation" aria-label="element tree"
role="navigation" aria-label="file tree"
role="main" aria-label="edit document"

There is room to negotiate exact label text and designations, but these
seem like a good starting point for discussion.


On Monday, April 20, 2015, Wayne Roddy <notifications@github.com> wrote:

> then we have the need for quick ui navigation:
>
>    - open search div
>    - focus on resource tree
>    - focus on element tree
>    - focus on file tree
>    - focus on top menu
>
> all seem like suitable time savers as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modxcms/a11y/issues/11#issuecomment-94516519>.
>


-- 
Paul Bohman

**Comment by dubrod** [comment]
those are all being cover under #22

**Comment by paulbohman** [comment]
Oh, right! Thanks.

On Monday, April 20, 2015, Wayne Roddy <notifications@github.com> wrote:

> those are all being cover under #22
> <https://github.com/modxcms/a11y/issues/22>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modxcms/a11y/issues/11#issuecomment-94526587>.
>


-- 
Paul Bohman

**Comment by kensgists** [comment]
This can get tricky, since sometimes shortcut keys can conflict with other applications' defined shortcuts and with quick key navigation in various assistive technologies. I think some high-level navigation shortcuts would make sense, especially getting to the search, top nav, and tree. 

Can I recommend that you make a preference for key combinations? For example, having Ctrl+Alt be the combo out of the box but then allowing a user to set preferences for just Ctrl or Ctrl+Alt+Shift. 

Also, many desktop apps allow for F6 to move between regions in the interface. This works in Word and in Acrobat, for example. To get something similar working in Adobe Connect, they implemented a combination of Alt+F6. Each press loops the user between the make chunks/pods of the interface.

**Comment by dubrod** [comment]
Started trying to make a few shortcuts. Like @kensgists said, making combos is effective.

I committed code that attempts to use `ctrl+option` to collapse and `ctrl+shift` to expand. Collapse works but expand doesn't. 

**Key Bindings:**

 - 1 binds to resource tree
 - 2 binds to element tree
 - Ctrl+Shift+N opens a new Resource page
 - Ctrl+Shift+T reloads the Resource Tree but i can not get it to expand.

**Comment by dubrod** [comment]
we have effectively handled all keyboard shortcuts and keyboard accessibility in other areas
