### ISSUE TITLE
Theme Switcher

### ISSUE THREAD

**Issue by rthrash** [modxcms/a11y#13]
"You are currently using the default Manager Theme. <link>Click here to switch to the accessible theme.</link>"

This would be hidden via CSS.

**Comment by electrickite** [comment]
IMHO, there should be two accessible ways to switch the manager theme to the enhanced version. The first would be an option during the installation process. The second would be something like what is suggested above.

**Comment by kensgists** [comment]
I'll echo Paul's comment -- "I hope you don't do that" with accessible v. inaccessible themes. Ideally, the "old" theme would be the "tired, inaccessible" one and the "new and improved" theme would be accessible to screen reader and keyboard users out of the box, maybe with the "enchance contrast" option in the theme settings. 

Trying to avoid the unfortunate, "second class" bifurcation many screen reader users and users with disabilities, generally, are all too used to. 

And Cory/electrickite I think makes a good suggestion. If it can be preferenced during install, then individual users would have less to fuss with post deployment.

**Comment by rthrash** [comment]
There is now a Dashboard widget with a pending update that will use the following text, which I hope captures the spirit and functional requirements. The a11y theme definitely should and will be a first-class UI.

> The _a11y_ theme enhances visual contrast, keyboard navigation and compatibility with screen readers. Use the select list to change your theme.
