### ISSUE TITLE
Login Page - Error Messages

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#23]
For compliance with Web Content Accessibility Guidelines (WCAG)

The feedback messages ("User not found...", "The username or password you entered is incorrect...") need to be read by screen readers when the page refreshes.

Option 1: One way to accomplish this is to force the keyboard focus onto the error message when the page reloads. The error message would need to have tabindex="-1" to effectively be able to receive the focus via JavaScript. <div id="alert-message" tabindex="-1">User not found...</div>. The message should precede the first relevant form field. If the username/password is incorrect, the message should appear above the username field. If the error occurs on the "Username or Email" field (after selecting "forgot password?" then the error message should appear directly above the "username or email" field, so that users hit tab once to go into that field.

Option 2: put the error message in the label of the relevant field, either by putting it in the <label> tag, or by using aria-label to refer to the message, e.g. refer to both the regular label and the message:
```
<div id="alert-message">User not found...</div>

<label for="username" id="username-label">Username</label> 

<input aria-label="alert-message username-label" ...>
```
Note that you would want to link the error message for the "username or email" field to that field directly, not to the "username" field. You would also want to make sure that keyboard focus goes to the "username or email" field and NOT to the top "username" field on page reload. In other words, make sure you're sending the keyboard focus to the correct field to match the error, and make sure the error message is associated with the appropriate field.
Also: Set aria-invalid="true" on the <input> element after the form has been submitted on all incorrect fields. Screen readers will say "invalid" to let users know they need to fix the field.

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#login

**Comment by kensgists** [comment]
Though first item in this thread is marked as "closed," note that the code snippet here has an error. aria-label takes a text value (what you want the screen reader to read aloud). aria-labelledby takes the id values. You want to use aria-labelledby in this circumstance.

**Comment by dubrod** [comment]
we actually didnt use this b/c we can't target error msgs to labels without a core change. Did you try the login form ?  I believe its working ok but would like a second opinion.

**Comment by dubrod** [comment]
@kensgists PING

**Comment by goldsky** [comment]
I have make some changes for this particular page:
https://github.com/goldsky/a11y/blob/9c21cad4d64005cd3a024063487102c51c48a7a4/manager/templates/a11y/security/login.tpl

May be this is related?
