### ISSUE TITLE
Color Contrast

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#27]
For compliance with Web Content Accessibility Guidelines (WCAG)

The color contrast ratio of the light-colored text in many places does not pass the WCAG standard of 4.5 to 1 for normal text of 3 to 1 for large text. The color contrast can be analyzed using automated tools such as FireEyes/WorldSpace http://worldspace.dequecloud.com and Wave http://wave.webaim.org

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#styles

**Comment by dubrod** [comment]
recent contrast feedback

- [ ] Inadequate contrast for the Search text within the search button. 
- [ ] Inadequate contrast in the context menu both when used via mouse or when moved through with the keyboard. 
- [ ] Inadequate contrast for unfocused state on all of the main-area expand/collapse downward facing triangles.

**Comment by rthrash** [comment]
The Context menus for the Tree still need additional contrast I think. Other than that I think we can close this one down and handle exceptions on a case-by-case basis.

**Comment by dubrod** [comment]
![image](https://cloud.githubusercontent.com/assets/595788/12617644/9c958446-c4de-11e5-874f-9a418511c8f7.png)
