### ISSUE TITLE
Font for people with dyslexia

### ISSUE THREAD

**Issue by mindeffects** [modxcms/a11y#32]
Maybe you might be interested in integrating the (free) font "dyslexiefont" as an alternative font into the manager? It helps people with dyslexia by making text better readable: http://www.dyslexiefont.com/en/dyslexia-font/
The results are really remarkable!

**Comment by rthrash** [comment]
That's a really cool suggestion … thanks Oliver!

**Comment by dubrod** [comment]
I emailed them for permission to use.

**Comment by dubrod** [comment]
I have started editing the welcome screen to include things like this. There is a toggle button for the font on the welcome screen.

**Comment by Mark-H** [comment]
Does it make sense to implement this as a setting instead of using cookies, so it can be enabled/disabled for specific users or groups with user (group) settings?

**Comment by dubrod** [comment]
go for it

**Comment by sottwell** [comment]
Actually there is considerable debate about this issue. And there are several free alternatives.

http://bigelowandholmes.typepad.com/bigelow-holmes/2014/11/typography-dyslexia.html
http://blog.dyslexia.com/good-fonts-for-dyslexia-an-experimental-study/
http://opendyslexic.org/

**Comment by dubrod** [comment]
added the open dyslexia font
