### ISSUE TITLE
[2.3] Manager Theme: Uberbar color contrast too low

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/a11y#37]
Moved from modxcms/revolution#11645

The color contrast between the background of the uberbar search field and the background color of the menu bar is too low to meet WCAG AA requirements. WCAG AA requires a contrast ration of 4.5:1, the current color scheme provides 1.48:1.

See http://webaim.org/resources/contrastchecker/

I am partially color blind and it is very hard to see the dark search field on the dark menu bar background or the "Search" text hint.

Related to #11608 but I wanted to call out the accessibility issues produced by low contrast color choices.

**Comment by dubrod** [comment]
can you give me a screenshot of which search bar your looking at? 
2.4 has a new search bar and a11y has its own search bar colors. 

Thanks.

**Comment by OptimusCrime** [comment]
Not my issue. It was originally opened by @electrickite

**Comment by electrickite** [comment]
When I opened the issue, I was looking at the search bar in the attached screenshot. This is from 2.3.3

![screen shot 2015-08-20 at 10 36 59 am](https://cloud.githubusercontent.com/assets/3449824/9386010/88458110-4727-11e5-96d2-0f982a532d6a.png)

**Comment by dubrod** [comment]
Thanks. we are not using that style in the a11y project, and the new 2.4 search created a small bug which i've already noted in issues. So I'll close this and you can continue commenting on the search bar in Issue #39
