### ISSUE TITLE
Search bar bug

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#39]
![a11y-2_4-search-bug](https://cloud.githubusercontent.com/assets/595788/9384639/df0572e2-471f-11e5-9f1f-2cb75aa030f9.gif)

new 2.4 search bar does the dropdown thing

**Comment by goldsky** [comment]
I'm still getting new awkward behavior.
If the ubarbar pops left, the left tree navigation got hidden, and then the entire body got pushed by some margin-right.
Are you getting the same one?
