### ISSUE TITLE
Link goes invisible on hover

### ISSUE THREAD

**Issue by sottwell** [modxcms/a11y#40]
User's link in the User Groups and Users tab goes invisible on hover (screenshot doesn't show mouse cursor)

Firefox 40.0.2 
OS X 10.9.5
MODX Revo 2.4.0

![screen shot 2015-08-21 at 8 28 41 am](https://cloud.githubusercontent.com/assets/1073780/9401892/b2357f2c-47de-11e5-83dc-bd630cdc72db.png)

**Comment by sottwell** [comment]
Hm. Update this. All links in the entire Manager are a pale blue and disappear on hover.

**Comment by sottwell** [comment]
Found the culprit. Line 65 of your sass/index.scss file which results in line 11625 of the index.css file
```body a:hover, body.x-border-layout-ct a:hover {
  color: #FFF;
}```

**Comment by dubrod** [comment]
fixed thank you Susan!
