### ISSUE TITLE
modx-resource-header Title needs to be H1 not H2

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#54]
Per the interface requirements image. 

`<h2>MODX Revolution</h2>`  and `<h2>New Document</h2>` under the div `modx-resource-header` need to be `<h1>`

**Comment by dubrod** [comment]
the Dashboard Title is in `manager/assets/modext/widgets/modx.panel.welcome.js`

Line 20 = `html: '<h1>'+dashboardName+'</h1>'`

This would be a core change, and would require the addition of `h1` to index.scss on line 130. 

BUT it is active on the cloud site right now.

**Comment by dubrod** [comment]
@theboxer i could not find the file to change the resource title markup though

**Comment by theboxer** [comment]
It's in `/manager/assets/modext/widgets/resource/modx.panel.resource.js` line 362

```
,getPageHeader: function(config) {
        config = config || {record:{}};
        return {
            html: '<h2>'+_('document_new')+'</h2>'
            ,id: 'modx-resource-header'
            ,cls: 'modx-page-header'
            ,border: false
            ,forceLayout: true
            ,anchor: '100%'
        };
    }
```

**Comment by theboxer** [comment]
Resource title updated. Dashboard title needs to be changed in core
