### ISSUE TITLE
Uberbar becomes <nav>

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#56]
`ul#modx-topnav` and `ul#modx-user-menu` need to be wrapped by

`<ul>` also gets `role="menu"`

```
<nav><h2 class="sr-only">Global Navigation</h2> 
 <ul>....
</nav>
```

**Comment by dubrod** [comment]
@kensgists   @paulbohman   hidden H2 is there and its wrapped.  please test

**Comment by dubrod** [comment]
@theboxer can you look at getting the `<ul>` under the uberbar to add `role="menu"`

**Comment by theboxer** [comment]
Should be there

**Comment by dubrod** [comment]
Ok slight change in order. I believe the # modx-topnav needs role="menubar" b/c its rendered horizontally and it will be [tab] key to move along. Where as the first UL will be key arrows to move along.

so:

```
<ul id="modx-topnav" role="menubar">
	<li id="limenu-site" class="top" role="menuitem" aria-haspopup="true">
		<a href="javascript:;">Content</a>
		<ul class="modx-subnav" role="menu">
			<li id="new_resource" role="menuitem">
```

we also have to add `aria-haspop="true"` when an `li` has a submenu

**Comment by theboxer** [comment]
@dubrod should be ready for review

**Comment by dubrod** [comment]
Awesome work. looks good to me. Labeling as Needs Testing for the stakeholders.
