### ISSUE TITLE
Toggle Element on Resource Tab Strip 

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#69]
Need the same **aria-expand , aria-controls, aria-label, SR only text, tabindex, and key press listener features** added to the x-tool-toggle that is on the resource page where document, tv, settings, etc is at.

**Comment by theboxer** [comment]
Should be there

**Comment by dubrod** [comment]
yup its there. nice work.

**Comment by dubrod** [comment]
just found a bug. if you close this panel and keep hitting tab it still goes through all the elements inside. i think we need to make it tabindex -1 so it skips it.

**Comment by dubrod** [comment]
@theboxer  this bring it down to 2 "tab presses" and you can see them focused. I think its ok to leave now. the only remaining element to change would be `x-tab-strip-wrap` to tabindex -1 and `x-tab-strip-active` to tabindex -1
