### ISSUE TITLE
Tree Gear Icon overrides keydown

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#76]
the gear seems to return to the parent context element if you hit anything other than tab while its highlighted. 

We must be able to hit the `up/left/right/down key arrow` at all times to toggle resource parents

**Comment by theboxer** [comment]
I can't reproduce it. Using Chrome Version 47.0.2526.106 (64-bit) on OS X

**Comment by dubrod** [comment]
change the gear icon trigger to `cmd+F10` per request.

`TAB` Key should close the current tree and focus the next. ( new issue coming )

**Comment by dubrod** [comment]
eliminate the need for the gear icon. cmd+f10 on a resource tree node will open its context menu.
