### ISSUE TITLE
Dyslexic Font Link Error

### ISSUE THREAD

**Issue by dubrod** [modxcms/a11y#83]
in console when triggering font.

`http://a11y.clients.modxcloud.com/manager/templates/a11y/css/templates/a11y/css/fonts/OpenDyslexic3-Regular-webfont.ttf`

**Comment by rthrash** [comment]
Double `templates/a11y/css/` leads to the open dyslexia font not loading and falling back to browser default.

**Comment by theboxer** [comment]
don't follow

**Comment by theboxer** [comment]
oh, now I see
